# -*- coding: utf-8 -*-
"""Campaign_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmQacyYV-9a-UHZvdkQhxRrXRnR67V5o
"""

# 📊 Ad Campaign Performance Optimization Project
# Dataset: KAG_conversion_data.csv (from Kaggle)

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------
# STEP 1: Load dataset
# ------------------------------
df = pd.read_csv("KAG_conversion_data.csv")

print("Dataset Shape:", df.shape)
print(df.head())

# ------------------------------
# STEP 2: Create metrics at Ad-level
# ------------------------------
df['CTR'] = df['Clicks'] / df['Impressions'].replace(0, 1)
df['CPC'] = df['Spent'] / df['Clicks'].replace(0, 1)
df['Conversion Rate'] = df['Total_Conversion'] / df['Clicks'].replace(0, 1)
df['ROI'] = df['Total_Conversion'] / df['Spent'].replace(0, 1)

print("\nAd-level Metrics:\n", df[['ad_id','CTR','CPC','Conversion Rate','ROI']].head())

# ------------------------------
# STEP 3: Aggregate by Campaign
# ------------------------------
campaign_perf = df.groupby('xyz_campaign_id').agg({
    'Impressions':'sum',
    'Clicks':'sum',
    'Spent':'sum',
    'Total_Conversion':'sum'
}).reset_index()

campaign_perf['CTR'] = campaign_perf['Clicks'] / campaign_perf['Impressions']
campaign_perf['CPC'] = campaign_perf['Spent'] / campaign_perf['Clicks'].replace(0, 1)
campaign_perf['Conversion Rate'] = campaign_perf['Total_Conversion'] / campaign_perf['Clicks'].replace(0, 1)
campaign_perf['ROI'] = campaign_perf['Total_Conversion'] / campaign_perf['Spent'].replace(0, 1)

print("\n📊 Campaign-Level Summary:\n", campaign_perf)

# ------------------------------
# STEP 4: Visualizations
# ------------------------------

# CTR by Campaign
plt.figure(figsize=(8,4))
plt.bar(campaign_perf['xyz_campaign_id'], campaign_perf['CTR'])
plt.xlabel("Campaign ID")
plt.ylabel("CTR")
plt.title("CTR by Campaign")
plt.show()

# ROI vs Spend
plt.figure(figsize=(8,4))
plt.scatter(campaign_perf['Spent'], campaign_perf['ROI'], s=100, alpha=0.7)
plt.xlabel("Spend")
plt.ylabel("ROI")
plt.title("ROI vs Spend")
plt.show()

# ------------------------------
# STEP 5: Audience Segmentation (Age x Gender)
# ------------------------------
segmentation = df.groupby(['age','gender']).agg({
    'Impressions':'sum',
    'Clicks':'sum',
    'Spent':'sum',
    'Total_Conversion':'sum'
}).reset_index()

segmentation['CTR'] = segmentation['Clicks'] / segmentation['Impressions'].replace(0, 1)
segmentation['CPC'] = segmentation['Spent'] / segmentation['Clicks'].replace(0, 1)
segmentation['Conversion Rate'] = segmentation['Total_Conversion'] / segmentation['Clicks'].replace(0, 1)
segmentation['ROI'] = segmentation['Total_Conversion'] / segmentation['Spent'].replace(0, 1)

print("\n👥 Audience Segmentation:\n", segmentation)

# CTR by Age Group
plt.figure(figsize=(8,4))
plt.bar(segmentation['age'], segmentation['CTR'])
plt.xlabel("Age Group")
plt.ylabel("CTR")
plt.title("CTR by Age Group")
plt.show()

# ------------------------------
# STEP 6: Simple Forecast (Budget Pacing Simulation)
# ------------------------------
campaign_perf['Expected_Spend'] = campaign_perf['Spent'] * 1.2  # simulate +20% budget
campaign_perf['Forecast_Conversions'] = campaign_perf['Conversion Rate'] * (campaign_perf['Clicks']*1.2)

print("\n📈 Forecast Results:\n", campaign_perf[['xyz_campaign_id','Spent','ROI','Expected_Spend','Forecast_Conversions']])